pipeline {
	agent any
	stages {

		stage('Create Kubernetes Cluster') {
			steps {
				withAWS(region:'eu-west-2', credentials:'aws_cred') {
					sh '''
						eksctl create cluster \
						--name KubernetesCluster \
						--version 1.17 \
						--region eu-west-2 \
						--nodegroup-name standard-workers \
						--node-type t3.medium \
						--nodes 2 \
						--nodes-min 1 \
						--nodes-max 3 \
					'''
				}
			}
		}

		stage('Configure kubectl') {
			steps {
				withAWS(region:'eu-west-2', credentials:'aws_cred') {
					sh '''
						aws --region eu-west-2 eks update-kubeconfig --name KubernetesCluster
					'''
				}
			}
		}

	}
}