apiVersion: apps/v1
kind: Deployment
metadata:
  name: app_capstone
  labels:
    app: app_capstone
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app_capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: app_capstone
    spec:
      containers:
        - image: lassina/app_capstone:lastest"
          imagePullPolicy: Always
          name: app_capstone
          ports:
          - containerPort: 80