apiVersion: v1
kind: Service
metadata:
  name: app_capstone
  labels:
    app: app_capstone
spec:
  type: LoadBalancer
  selector:
    app: app_capstone
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP