apiVersion: v1
kind: Service
metadata:
  name: app-capstone
  labels:
    app: app-capstone
spec:
  type: LoadBalancer
  selector:
    app: app-capstone
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP